-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 13:34:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteka` DEFAULT CHARACTER SET utf8 ;
USE `biblioteka` ;

-- -----------------------------------------------------
-- Table `biblioteka`.`DZIALY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`DZIALY` (
  `id_dzialu` INT NOT NULL AUTO_INCREMENT,
  `nazwa_dzialu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dzialu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`TYTULY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`TYTULY` (
  `id_tytulu` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(250) NULL,
  `id_dzialu` INT NOT NULL,
  PRIMARY KEY (`id_tytulu`, `id_dzialu`),
    FOREIGN KEY (`id_dzialu`)
    REFERENCES `biblioteka`.`DZIALY` (`id_dzialu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`AUTORZY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`AUTORZY` (
  `id_autora` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  PRIMARY KEY (`id_autora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`KSIAZKI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`KSIAZKI` (
  `id_ksiazki` INT NOT NULL AUTO_INCREMENT,
  `id_tytulu` INT NOT NULL,
  `id_autora` INT NOT NULL,
  PRIMARY KEY (`id_ksiazki`, `id_tytulu`, `id_autora`),
    FOREIGN KEY (`id_tytulu`)
    REFERENCES `biblioteka`.`TYTULY` (`id_tytulu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KSIAZKI_AUTORZY1`
    FOREIGN KEY (`id_autora`)
    REFERENCES `biblioteka`.`AUTORZY` (`id_autora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
